CET-537/fix: Issue with saving address for logged in customers
When a customer is logged in, the address fails to save which is currently causing issues for some of our merchants.

```
Error: Call to undefined method Magento\Customer\Model\Data\Address::save() in /bitnami/magento/app/code/Two/Gateway/Controller/Payment/Confirm.php:162
Stack trace:
```

![Screenshot 2024-12-05 at 09.16.42.png](https://uploads.linear.app/dec93f74-b00f-44c6-a396-24c81f5fe6fd/42d4061f-0b22-4665-8b6e-406e14000b28/73b1181a-a299-47d5-90a3-1699ccf91074)